# Pandas for Data Analysis

# Create DataFrames

In [303]:
import pandas as pd

data = pd.DataFrame({
    'IDs': [1,2,3,4,5],
    'Names': ['farah', 'moh', 'abd', 'salma', 'doaa'],
    'Ages': [24,32,19,20,21]
})

print(data)

   IDs  Names  Ages
0    1  farah    24
1    2    moh    32
2    3    abd    19
3    4  salma    20
4    5   doaa    21

In [304]:
# DataFrame Overview
# info() -> print all columns, there count, types , whether there is nulls
print(data.info())  
#describe() -> statistical info
print(data.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   IDs     5 non-null      int64
 1   Names   5 non-null      object
 2   Ages    5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None
            IDs       Ages
count  5.000000   5.000000
mean   3.000000  23.200000
std    1.581139   5.263079
min    1.000000  19.000000
25%    2.000000  20.000000
50%    3.000000  21.000000
75%    4.000000  24.000000
max    5.000000  32.000000

In [305]:
# # to set the IDs to the index column 
# data = data.set_index('IDs')
# print(data)

# Reshaping data
* melt()
* pivot()
* concat()
* concat() along columns

In [306]:
# melt() -> btsaya7 el columns, gather columns into rows

data3 = pd.DataFrame(
    {
        'Names' : ['alice', 'bob', 'charlie'],
        'Cairo' : [1, 0, 1],
        'Alex' : [0, 1, 0]
    }
)

data_melted = pd.melt(data3, id_vars=["Names"], var_name='City', value_name='Visited')
print(data_melted)

     Names   City  Visited
0    alice  Cairo        1
1      bob  Cairo        0
2  charlie  Cairo        1
3    alice   Alex        0
4      bob   Alex        1
5  charlie   Alex        0

In [307]:
# pivot() -> byrag3 el melt lel original, spread rows into columns

data_pivot = data_melted.pivot(index='Names', columns='City', values='Visited')
data_pivot['Names'] = data_pivot.index
data_pivot = data_pivot.reset_index(drop=True) # 34n el Names matkonsh el index htkon column, el index htkon arqam 3adi [0,1,2]
print(data_pivot)

City  Alex  Cairo    Names
0        0      1    alice
1        1      0      bob
2        0      1  charlie

In [308]:
# concat()
data2= pd.DataFrame({
    'IDs': [6, 7],
    'Names': ['frank', 'grace'],
    'Ages': [20,30]
})

data = pd.concat([data, data2], ignore_index=True)
print(data)

   IDs  Names  Ages
0    1  farah    24
1    2    moh    32
2    3    abd    19
3    4  salma    20
4    5   doaa    21
5    6  frank    20
6    7  grace    30

In [309]:
# # concatenate along columns

# Method 1
data['City'] = ['Cairo', 'Alex', 'Cairo', 'Alex', 'Cairo', 'Alex', 'Cairo']
print(data)

# # Method 2
# # axis=1 means add to columns, axis=0 by default and means add to rows
# data = pd.concat([data, data2], axis=1) 
# print(data)

   IDs  Names  Ages   City
0    1  farah    24  Cairo
1    2    moh    32   Alex
2    3    abd    19  Cairo
3    4  salma    20   Alex
4    5   doaa    21  Cairo
5    6  frank    20   Alex
6    7  grace    30  Cairo

In [310]:
# Sorting
data = data.sort_values(by='Ages', ascending=False) # By default ascending=True
print(data)
print('=============')

# Renaming  -> rename column
data = data.rename(columns={'IDs':'ID', 'Names':'Name', 'Ages':'Age', 'City':'Location'})
print(data)
print('=============')

# drop columns
data = data.drop(columns=['ID'])
print(data)
print('=============')

# drop rows 
data = data.drop(index=[0, 1])
print(data)

   IDs  Names  Ages   City
1    2    moh    32   Alex
6    7  grace    30  Cairo
0    1  farah    24  Cairo
4    5   doaa    21  Cairo
3    4  salma    20   Alex
5    6  frank    20   Alex
2    3    abd    19  Cairo
=============
   ID   Name  Age Location
1   2    moh   32     Alex
6   7  grace   30    Cairo
0   1  farah   24    Cairo
4   5   doaa   21    Cairo
3   4  salma   20     Alex
5   6  frank   20     Alex
2   3    abd   19    Cairo
=============
    Name  Age Location
1    moh   32     Alex
6  grace   30    Cairo
0  farah   24    Cairo
4   doaa   21    Cairo
3  salma   20     Alex
5  frank   20     Alex
2    abd   19    Cairo
=============
    Name  Age Location
6  grace   30    Cairo
4   doaa   21    Cairo
3  salma   20     Alex
5  frank   20     Alex
2    abd   19    Cairo

# Selection from dataframe

In [311]:
data = pd.DataFrame({
    'ID': [1,2,3,4,5, 6, 7],
    'Name': ['farah', 'moh', 'abd', 'salma', 'doaa', 'frank', 'grace'],
    'Age': [24,32,19,20,21, 20, 30],
    'City': ['Cairo', 'Alex', 'Cairo', 'Alex', 'Cairo', 'Alex', 'Cairo']
})

print(data)

   ID   Name  Age   City
0   1  farah   24  Cairo
1   2    moh   32   Alex
2   3    abd   19  Cairo
3   4  salma   20   Alex
4   5   doaa   21  Cairo
5   6  frank   20   Alex
6   7  grace   30  Cairo

In [312]:
# select based on a condition
data[data['Age']>21]

   ID   Name  Age   City
0   1  farah   24  Cairo
1   2    moh   32   Alex
6   7  grace   30  Cairo

In [313]:
# select certain rows -> 'iloc' means based on the 'index location'
data.iloc[:3]

   ID   Name  Age   City
0   1  farah   24  Cairo
1   2    moh   32   Alex
2   3    abd   19  Cairo

In [314]:
# select based on multiple criterias
data[(data['Age'] > 21) & (data['City'] == 'Cairo')]

   ID   Name  Age   City
0   1  farah   24  Cairo
6   7  grace   30  Cairo

In [315]:
# Read csv data
data_netflix = pd.read_csv(r'D:\IBM Data Scienctist DEPI\DEPI_Projects\data\netflix_movies.csv')
# return 1st 5 rows
data_netflix.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [316]:
print(data_netflix.info())
print("===========")
print(data_netflix.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB
None
===========
       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [317]:
# return 10 random smaples of data
data_netflix.sample(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1201,s1202,TV Show,Abla Fahita: Drama Queen,NaN,"Bassem Samra, Donia Maher, Zeina Mansour, Osam...",Egypt,"March 15, 2021",2021,TV-14,1 Season,"Crime TV Shows, International TV Shows, TV Com...","Falsely incriminated, Abla Fahita is separated..."
4737,s4738,Movie,The Blue Umbrella,Vishal Bhardwaj,"Pankaj Kapur, Shreya Sharma, Dolly Ahluwalia, ...",India,"August 2, 2018",2005,TV-PG,90 min,"Children & Family Movies, Dramas, Independent ...",A charming allegory based on a novella by Rusk...
6469,s6470,TV Show,Chill with Bob Ross,NaN,Bob Ross,NaN,"December 1, 2016",1994,TV-G,1 Season,TV Shows,Iconic artist and master of relaxation Bob Ros...
3374,s3375,Movie,It Takes a Lunatic,Billy Lyons,NaN,"United States, United Kingdom, Germany","October 25, 2019",2019,TV-MA,127 min,Documentaries,The extraordinary life of beloved acting teach...
7302,s7303,Movie,Lifechanger,Justin McConnell,"Lora Burke, Jack Foley, Bill Oberst Jr., Elits...",Canada,"May 28, 2019",2018,TV-MA,84 min,"Horror Movies, Independent Movies, Thrillers","A shapeshifter has to kill, then inhabit his v..."
8758,s8759,TV Show,World's Busiest Cities,NaN,"Anita Rani, Ade Adepitan, Dan Snow",United Kingdom,"February 1, 2019",2017,TV-PG,1 Season,"British TV Shows, Docuseries","From Moscow to Mexico City, three BBC journali..."
6271,s6272,Movie,Bedtime Stories,Adam Shankman,"Adam Sandler, Keri Russell, Guy Pearce, Russel...",United States,"March 5, 2019",2008,PG,100 min,"Children & Family Movies, Comedies",Skeeter's life is turned upside down when the ...
6544,s6545,Movie,Cult of Chucky,Don Mancini,"Fiona Dourif, Michael Therriault, Adam Hurtig,...",United States,"October 3, 2017",2017,R,90 min,Horror Movies,Following a string of murders in the asylum wh...
783,s784,Movie,Carnaval,Leandro Neri,"Giovana Cordeiro, Gkay, Bruna Inocencio, Samya...",Brazil,"June 2, 2021",2021,TV-MA,95 min,"Comedies, International Movies, Music & Musicals","After a breakup, an influencer takes her frien..."
4555,s4556,Movie,The Meaning of Monty Python,Albert Sharpe,NaN,United Kingdom,"October 2, 2018",2013,TV-MA,60 min,Documentaries,Five Pythons reflect on their creative process...

In [318]:
# return 1% from data
data_netflix.sample(frac=0.1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
4688,s4689,Movie,The After Party,Ian Edelman,"Kyle Harvey, Harrison Holzer, Teyana Taylor, S...",United States,"August 24, 2018",2018,TV-MA,90 min,"Comedies, Music & Musicals",An aspiring rapper and his best friend/manager...
430,s431,TV Show,Sexy Beasts,NaN,NaN,NaN,"July 21, 2021",2021,TV-14,1 Season,"British TV Shows, International TV Shows, Real...","Hoping to say goodbye to superficial dating, r..."
3776,s3777,Movie,Miranda Sings Live…Your Welcome,Marcus Raboy,Colleen Ballinger,United States,"June 4, 2019",2019,TV-14,62 min,Stand-Up Comedy,Viral video star Miranda Sings and her real-wo...
1038,s1039,TV Show,Dancing Angels,NaN,NaN,NaN,"April 15, 2021",2016,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...",A group of aspiring young musicians yearn for ...
4370,s4371,Movie,The Tribe,Fernando Colomo,"Paco León, Carmen Machi, Luis Bermejo, Maribel...",Spain,"November 21, 2018",2018,TV-MA,91 min,"Comedies, International Movies",An executive-turned-viral sensation loses his ...
...,...,...,...,...,...,...,...,...,...,...,...,...
4564,s4565,Movie,Dushman,Shagufta Rafique,"Kartar Cheema, Jashan Singh, Sakshi Gulati, Gu...",NaN,"October 1, 2018",2017,TV-14,141 min,"Dramas, International Movies",An Indian hotel waiter forms an unlikely bond ...
5034,s5035,Movie,Agustín Aristarán: Soy Rada,Mariano Baez,Agustín Aristarán,Argentina,"February 16, 2018",2018,TV-MA,60 min,Stand-Up Comedy,"Argentine comedian Agustín ""Radagast"" Aristará..."
8275,s8276,Movie,The Devil and Father Amorth,William Friedkin,NaN,"Italy, United States","July 23, 2018",2017,TV-PG,69 min,"Documentaries, Horror Movies","In Rome, ""Exorcist"" director William Friedkin ..."
6392,s6393,Movie,Burning,Lee Chang-dong,"Yoo Ah-in, Steven Yeun, Jun Jong-seo, Kim Soo-...","South Korea, Japan","April 29, 2019",2018,TV-MA,148 min,"Dramas, Independent Movies, International Movies",An aspiring writer goes to the airport to pick...
3429,s3430,Movie,Fractured,Brad Anderson,"Sam Worthington, Lily Rabe, Stephen Tobolowsky...",United States,"October 11, 2019",2019,TV-MA,100 min,Thrillers,After his wife and injured daughter disappear ...

In [319]:
# return last 5 rows
data.tail()

   ID   Name  Age   City
2   3    abd   19  Cairo
3   4  salma   20   Alex
4   5   doaa   21  Cairo
5   6  frank   20   Alex
6   7  grace   30  Cairo

In [320]:
# return the 5 largest release_year films
data_netflix.nlargest(5,'release_year')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...

In [ ]:
data_netflix[['title', 'release_year', 'rating']]

                      title  release_year rating
0      Dick Johnson Is Dead          2020  PG-13
1             Blood & Water          2021  TV-MA
2                 Ganglands          2021  TV-MA
3     Jailbirds New Orleans          2021  TV-MA
4              Kota Factory          2021  TV-MA
...                     ...           ...    ...
8802                 Zodiac          2007      R
8803            Zombie Dumb          2018  TV-Y7
8804             Zombieland          2009      R
8805                   Zoom          2006     PG
8806                 Zubaan          2015  TV-14

[8807 rows x 3 columns]

In [ ]:
# return and filter rows using RegEx
# return all rows with films 'titles' start with 'The'
data_netflix[data_netflix['title'].str.contains('^The', regex=True)]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...
35,s36,Movie,The Father Who Moves Mountains,Daniel Sandu,"Adrian Titieni, Elena Purea, Judith State, Val...",NaN,"September 17, 2021",2021,TV-MA,110 min,"Dramas, International Movies, Thrillers",When his son goes missing during a snowy hike ...
36,s37,Movie,The Stronghold,Cédric Jimenez,"Gilles Lellouche, Karim Leklou, François Civil...",NaN,"September 17, 2021",2021,TV-MA,105 min,"Action & Adventure, Dramas, International Movies","Tired of the small-time grind, three Marseille..."
47,s48,TV Show,The Smart Money Woman,Bunmi Ajakaiye,"Osas Ighodaro, Ini Dima-Okojie, Kemi Lala Akin...",NaN,"September 16, 2021",2020,TV-MA,1 Season,"International TV Shows, Romantic TV Shows, TV ...",Five glamorous millennials strive for success ...
...,...,...,...,...,...,...,...,...,...,...,...,...
8569,s8570,Movie,The Young Vagabond,Sze Yu Lau,"Chia-Hui Liu, Wong Yu, Jason Pai Piao, Lung We...",Hong Kong,"August 16, 2018",1985,TV-14,85 min,"Action & Adventure, Comedies, International Mo...","To avenge his master, a wine-loving young man ..."
8570,s8571,Movie,Theater of Life,Peter Svatek,Massimo Bottura,Canada,"July 18, 2017",2016,TV-PG,94 min,Documentaries,This documentary follows chef Massimo Bottura ...
8571,s8572,Movie,Theeram,Saheed Arafath,"Pranav Ratheesh, Maria Yohannan, Askar Ameer, ...",India,"July 1, 2018",2017,TV-14,104 min,"Dramas, International Movies, Romantic Movies",An auto rickshaw driver harbors a deep affecti...
8572,s8573,Movie,"Thelonious Monk: Straight, No Chaser",Charlotte Zwerin,"Thelonious Monk, Samuel E. Wright",United States,"November 1, 2019",1988,PG-13,89 min,"Documentaries, Music & Musicals",The spotlight shines on iconic jazz pianist an...
8573,s8574,Movie,Theo Who Lived,David Shisgall,NaN,United States,"December 16, 2016",2016,TV-14,86 min,Documentaries,American journalist Theo Padnos retraces the M...

In [328]:
# use query to filter data
data_netflix.query('release_year > 2000')

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...