In [1]:
import pandas as pd 

df = pd.read_csv('D:\IBM Data Scienctist DEPI\DEPI_Projects\data\WLD_RTFP_country_2023-10-02.csv')

df.head()

<>:3: SyntaxWarning: invalid escape sequence '\I'
<>:3: SyntaxWarning: invalid escape sequence '\I'
C:\Users\fxrxh\AppData\Local\Temp\ipykernel_19460\2258930448.py:3: SyntaxWarning: invalid escape sequence '\I'
  df = pd.read_csv('D:\IBM Data Scienctist DEPI\DEPI_Projects\data\WLD_RTFP_country_2023-10-02.csv')

   Open  High   Low  Close  Inflation      country ISO3        date
0  0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-01-01
1  0.53  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-02-01
2  0.54  0.54  0.53   0.53        NaN  Afghanistan  AFG  2007-03-01
3  0.53  0.55  0.53   0.55        NaN  Afghanistan  AFG  2007-04-01
4  0.56  0.57  0.56   0.57        NaN  Afghanistan  AFG  2007-05-01

In [2]:
from mysql.connector import connect

# Connect to MySQL server (not to a specific database)
db = connect(
    host='localhost',
    port=3307,
    user='root',
    password='root'
)

cursor = db.cursor()
cursor.execute("CREATE DATABASE IF NOT EXISTS depi3;")
db.commit()
cursor.close()
db.close()

In [3]:
from sqlalchemy import create_engine

db = create_engine('mysql+pymysql://root:root@localhost:3307/depi3')

In [4]:
df.to_sql('wld_country', con=db, if_exists='replace', index=False)

4798

In [5]:
from mysql.connector import connect

db = connect(
    host='localhost',
    port = 3307,
    user='root',          
    password='root', 
    database='depi3'    
)

cursor = db.cursor()
cursor.execute("SELECT * FROM wld_country LIMIT 5")

rows = cursor.fetchall()
for row in rows:
    print(row)

(0.53, 0.54, 0.53, 0.53, None, 'Afghanistan', 'AFG', '2007-01-01')
(0.53, 0.54, 0.53, 0.53, None, 'Afghanistan', 'AFG', '2007-02-01')
(0.54, 0.54, 0.53, 0.53, None, 'Afghanistan', 'AFG', '2007-03-01')
(0.53, 0.55, 0.53, 0.55, None, 'Afghanistan', 'AFG', '2007-04-01')
(0.56, 0.57, 0.56, 0.57, None, 'Afghanistan', 'AFG', '2007-05-01')

In [6]:
import pandas as pd
from sqlalchemy import create_engine

#create connection to the database
engine = create_engine('mysql+pymysql://root:root@localhost:3307/depi3')

#execute sql query and display results
result_df = pd.read_sql("SELECT * FROM wld_country LIMIT 5", engine)
print("First 5 rows from wld-country table:")
display(result_df)

First 5 rows from wld-country table:

   Open  High   Low  Close Inflation      country ISO3        date
0  0.53  0.54  0.53   0.53      None  Afghanistan  AFG  2007-01-01
1  0.53  0.54  0.53   0.53      None  Afghanistan  AFG  2007-02-01
2  0.54  0.54  0.53   0.53      None  Afghanistan  AFG  2007-03-01
3  0.53  0.55  0.53   0.55      None  Afghanistan  AFG  2007-04-01
4  0.56  0.57  0.56   0.57      None  Afghanistan  AFG  2007-05-01

# Magic Lines

In [7]:
# # by3rafak command mo3ayan hayakhod wa2t ad eh fl execution
# %%timeit 

%load_ext sql

# Procedures
# What is procedures: 
-> predefined set of SQL statements that you can save in the database and execute repeatedly as a single unit. It’s like a function in programming, but it runs on the database server and can include complex logic.

# When to Use Procedures

* When you have repetitive queries or operations that multiple applications or users need.

* When you need complex operations that involve multiple steps (select, update, insert, delete).

* When you want to hide implementation details and give a simple interface to end-users.

* When you need transaction control: you can ensure multiple SQL operations succeed or fail together.

In [ ]:
# this will create a stored procedure named `replace_null_with_zero` that takes two parameters: the name of the table 'wld-country'and the name of the column where you want to replace NULL values with zero 'Inflation'.
cursor.execute("""
CREATE PROCEDURE replace_null_with_zero(table_name VARCHAR(255), column_name VARCHAR(255))
BEGIN
    SET @table = table_name;
    SET @column = column_name;
    set @sql = CONCAT('UPDATE ', @table, ' SET ', @column, ' = COALESCE(', @column, ', 0)');
    PREPARE stmt FROM @sql;
    EXECUTE stmt;
    DEALLOCATE PREPARE stmt;
END;

""")

In [ ]:
# this will apply the stored procedure to the 'wld-country' table and replace NULL values in the 'Inflation' column with zero.
cursor.callproc('replace_null_with_zero', ("wld_country", "Inflation"))

('wld_country', 'Inflation')

In [12]:
cursor.execute("SELECT * FROM wld_country LIMIT 5")
rows = cursor.fetchall()
for row in rows:
    print(row)

(0.53, 0.54, 0.53, 0.53, 0.0, 'Afghanistan', 'AFG', '2007-01-01')
(0.53, 0.54, 0.53, 0.53, 0.0, 'Afghanistan', 'AFG', '2007-02-01')
(0.54, 0.54, 0.53, 0.53, 0.0, 'Afghanistan', 'AFG', '2007-03-01')
(0.53, 0.55, 0.53, 0.55, 0.0, 'Afghanistan', 'AFG', '2007-04-01')
(0.56, 0.57, 0.56, 0.57, 0.0, 'Afghanistan', 'AFG', '2007-05-01')